### ISSUE TITLE
Conditioning on the diffusion step

### ISSUE THREAD

**Issue by eloimoliner** [HazyResearch/state-spaces#10]
Hello,

I'm considering trying your Sashimi model as the backbone of a diffusion model for audio generation. There is a detail I couldn't find in the paper, neither in the code (maybe I didn't look enough). How do you condition the model to the diffusion timestep? Do you do the same as in diffwave? (Element-wise addition of the diffusion-step embedding at each layer) Or use something similar to a FiLM layer , as in WaveGrad?

**Comment by albertfgu** [comment]
Hi, we use the exact conditioning method as in DiffWave. We didn't experiment with anything else. It's an oversight that this didn't appear in the standalone code; we'll release an updated version soon.

**Comment by albertfgu** [comment]
On more consideration it will take a while before I'm able to get to a releasable model for Sashimi+Diffwave. Hopefully the above description is enough to start with an implementation if you're interested. Feel free to correspond with us directly for more detailed questions about the implementation.

**Comment by albertfgu** [comment]
As part of the ongoing S4 v3 release, I decided to clean up and release my implementation of Sashimi+Diffwave at https://github.com/albertfgu/diffwave-sashimi. Apologies for not releasing it earlier

**Comment by eloimoliner** [comment]
That's great, thanks!
