### ISSUE TITLE
rfft() padding

### ISSUE THREAD

**Issue by jchia** [HazyResearch/state-spaces#103]
In models/s4/s4.py:1719-1722:
```
        k_f = torch.fft.rfft(k, n=l_kernel+L) # (C H L)
        x_f = torch.fft.rfft(x, n=l_kernel+L) # (B H L)
        y_f = contract('bhl,chl->bchl', x_f, k_f)
        y = torch.fft.irfft(y_f, n=l_kernel+L)[..., :L] # (B C H L)

```

I see that the signal and kernel are padded to be `l_kernel+L` long. If I understand correctly, actually `l_kernel+L-1` is enough. Is there a special reason to use `l_kernel+L`? Is it for equational simplicity?

**Comment by albertfgu** [comment]
Yes, I've always done that because its simpler. It may make a difference in speed because you want things to be nice lengths (powers of 2), but I've never tested the alternative

**Comment by albertfgu** [comment]
Feel free to make a PR!

**Comment by albertfgu** [comment]
Sorry for the delay, the PR has been merged. Thanks!
