### ISSUE TITLE
Issue on windows

### ISSUE THREAD

**Issue by lord644** [HazyResearch/state-spaces#107]
Does that codebase can run on windows platform ? I get the issue

wandb.errors.UsageError: Settings field `start_method`: 'fork' not in ['thread',
 'spawn']

caused by

train.py, line 635, in create_trainer
    settings=wandb.Settings(start_method="fork")

**Comment by albertfgu** [comment]
I've never tested it on Windows and I'm unable run it there. This sounds like it might be an issue with `wandb` and Windows. You can try removing that particular flag to start (the `start_method="fork"` line)

**Comment by lord644** [comment]
thanks, on windows platform it's actually equivalent to set 
`settings=wandb.Settings(start_method="thread")`

the next issue I came across is related to lambda functions serialization performed in basic.py, e.g.
`torchvision.transforms.Lambda(lambda x: x.view(self.d_input, self.L).t())`
has to be replaced with a named function
torchvision.transforms.Lambda(myfunc)

and that's it, train.py runs with default config

**Comment by albertfgu** [comment]
Great, thanks for the report! Hopefully this helps anyone else with this issue.
