### ISSUE TITLE
Multi GPU training

### ISSUE THREAD

**Issue by lzmax888** [HazyResearch/state-spaces#11]
Hi,

Is there any way to train S4 with multiple GPUs? I have 2 GPUs, but only one of them is working.

Thanks

**Comment by krandiash** [comment]
Hi, just pass in the `trainer.gpus` flag to the script e.g. `trainer.gpus=2` in your case.

**Comment by tkella47** [comment]
Does this work with multi node multigpu setups?

**Comment by albertfgu** [comment]
I haven't tested multi-node.
