### ISSUE TITLE
does s4_simple.py implement the method explained in the blog?

### ISSUE THREAD

**Issue by xonobo** [HazyResearch/state-spaces#112]
There is a link to s4_simple in [this blog](https://hazyresearch.stanford.edu/blog/2022-06-11-simplifying-s4). However, I cannot match the Chebyshev initialization explained in the blog with the [code](https://github.com/HazyResearch/state-spaces/blob/89f8167bafcf7808467d80a19fa55fee4154578e/src/models/sequence/ss/s4_simple/s4_simple.py#L40-L45) . 

In the code, `theta` values are multiplied with `a` values (`h_scales`). I expect them to be just `angles` according to blog.

Any guidance or explanation is appreciated.

**Comment by albertfgu** [comment]
"S4 simple" is not officially supported by this codebase and I'm not sure about its details. To my best knowledge, it is a close variant of S4D-Lin ([Paper](https://arxiv.org/abs/2206.11893), [Blog](https://srush.github.io/annotated-s4/s4d.html)). You may have better luck asking the [Safari team](https://github.com/HazyResearch/safari) about that particular line of code.
