### ISSUE TITLE
verifying the outputs of S4 in convolutional and recursive modes

### ISSUE THREAD

**Issue by xonobo** [HazyResearch/state-spaces#115]
I am trying to verify the equality of the outputs of the S4 layers for convolutional and recursive modes. According to my understanding, the forward method of the models uses the convolutional mode while the step method of the models uses the recursive mode. 

I just forked the repo and made a [dummy PR ](https://github.com/HazyResearch/state-spaces/pull/114/files)to show my verification steps.

I just tried the s4 model used for the BIDMC dataset. For the model, removed the bidirectional option and replaced the decoder with a simple linear layer. 

Here is my verification method:
https://github.com/xonobo/state-spaces/blob/9d0bd18b917fb9ca7111aa4956f974a109add50b/train.py#L701-L727 

I got a huge difference like 51.8991.

What am I doing wrong or am I missing any step in converting the S4 model from convolutional to recursive mode? 

Thanks in advance.

**Comment by albertfgu** [comment]
Did you check whether the outputs are closer for shorter sequences, and print the actual outputs to check? If they agree for short sequences, then it's possible that the differences are caused by numerical errors. This is always a potential issue for autoregressive models, although in practice we haven't seen issues.

**Comment by xonobo** [comment]
I checked the first 5 outputs and they are like these
```
First 5 output of forward: [0.38340651988983154, 0.37299948930740356, 0.3593390882015228, 0.3562837243080139, 0.38826751708984375]
First 5 output of step: [0.4338204860687256, 0.3899288773536682, 0.2777487635612488, 0.2168724536895752, 0.3204551041126251]
tensor(51.8991)
```

In my opinion, it does not look like a numerical error. 

I also focused on the first s4_block of the model. Here is the [code of that trial](https://github.com/xonobo/state-spaces/blob/1b279084e7da1a56a76459a7e0c6d5a4063bb12f/train.py#L694-L723) and its comparison.
```
Fist 5 output of forward (s4block): [-0.16247951984405518, -0.17739912867546082, -0.20097337663173676, -0.20007237792015076, -0.22281552851200104]
Fist 5 output of step  (s4block): [-0.2812332510948181, -0.2845004200935364, -0.2820417881011963, -0.27096420526504517, -0.3057439923286438]
tensor(299.9709)
```

If there is any sample code snippet to verify the equality for any kind of S4 layer, I can go over that example.

**Comment by albertfgu** [comment]
That looks like an issue with the stepping. Here's the test in my internal repo which works fine last I checked.

```
if __name__ == '__main__':
    import sys
    import pathlib
    p = pathlib.Path().absolute()
    print("Adding path: ", p)
    sys.path.append(str(p))

import torch
from src.models.sequence.modules.s4block import S4Block

def test_state(random_init=False, **kwargs):
    # B = 1
    # H = 64
    # N = 64
    # L = 1024
    B = 2
    H = 3
    N = 4
    L = 8
    s4 = S4Block(H, d_state=N, l_max=L, **kwargs)
    s4.to(device)
    s4.eval()
    # for module in s4.modules():
    #     if hasattr(module, '_setup_step'): module._setup_step()
    s4.setup_step()

    u = torch.ones(B, H, L).to(device)
    initial_state = s4.default_state(B)
    if random_init:
        if initial_state.size(-1) == N:
            initial_state = initial_state[..., :N//2]
            initial_state = torch.randn_like(initial_state)
            initial_state = torch.cat([initial_state, initial_state.conj()], dim=-1)
        else:
            initial_state = torch.randn_like(initial_state)

    state = initial_state.clone()
    y, final_state = s4(u, state=state)
    print("output:\n", y, y.shape)
    print("final state:\n", final_state, final_state.shape)

    # Use Stepping
    # for module in s4.modules():
    #     if hasattr(module, '_setup_step'): module._setup_step()
    s4.setup_step()
    state = initial_state.clone()
    ys = []
    for u_ in torch.unbind(u, dim=-1):
        y_, state = s4.step(u_, state=state)
        ys.append(y_)
    ys = torch.stack(ys, dim=-1)
    print("step outputs:\n", ys)
    print("step final state:\n", state)

    # Use Chunking

    chunks = 4
    state = initial_state.clone()
    ys = []
    for u_ in u.chunk(chunks, dim=-1):
        y_, state = s4(u_, state=state)
        ys.append(y_)
    ys = torch.cat(ys, dim=-1)
    print("chunk outputs:\n", ys)
    print("chunk final state:\n", state)
    print("chunk output error:")
    utils.compare_outputs(y, ys)
    print("chunk final state error:")
    utils.compare_outputs(final_state, state)


if __name__ == '__main__':
    from benchmark import utils
    torch.manual_seed(42)

    device = 'cuda' # 'cpu'
    device = torch.device(device)

    # test_state(random_init=True, mode='dense', init='legt', rank=2, channels=2)
    # test_state(random_init=True, mode='dplr', init='legt', rank=2, channels=2)
    # test_state(random_init=False, mode='diag', init='legs', rank=1)
    test_state(random_init=True, mode='diag', init='legs', rank=1, disc='zoh', channels=3)
```

You can also test in yours initializing using the simpler diagonal kernel to see if the problem is with DPLR.
Also I forget if the default argument is `transposed=True` or `transposed=False`. If it's `transposed=True` then the shapes of the tensors you're passing in is incorrect.

**Comment by xonobo** [comment]
I have difficulty in finding out this part
`from benchmark import utils`

**Comment by albertfgu** [comment]
Those are other internal utilities that shouldn't be essential, just comment it out.

**Comment by xonobo** [comment]
Just skipped that and checked the outputs of step and forward mode. Comparing y with ys value before the `# Use chunking` part,  I got quite different results.

y = 
```
tensor([[[-0.2190, -0.2190, -0.2189, -0.2187, -0.2186, -0.2184, -0.2182,
          -0.2179],
         [ 0.2135,  0.2130,  0.2125,  0.2120,  0.2114,  0.2108,  0.2102,
           0.2096],
         [-0.2103, -0.2107, -0.2110, -0.2114, -0.2118, -0.2122, -0.2125,
          -0.2129]],

        [[-0.2190, -0.2190, -0.2189, -0.2187, -0.2186, -0.2184, -0.2182,
          -0.2179],
         [ 0.2135,  0.2130,  0.2125,  0.2120,  0.2114,  0.2108,  0.2102,
           0.2096],
         [-0.2103, -0.2107, -0.2110, -0.2114, -0.2118, -0.2122, -0.2125,
          -0.2129]]], device='cuda:0', grad_fn=<ReshapeAliasBackward0>)
```

ys=
```
tensor([[[-0.4376, -0.4372, -0.4368, -0.4363, -0.4356, -0.4349, -0.4341,
          -0.4332],
         [ 0.3223,  0.3214,  0.3204,  0.3193,  0.3182,  0.3170,  0.3157,
           0.3143],
         [-0.1223, -0.1218, -0.1213, -0.1207, -0.1202, -0.1196, -0.1190,
          -0.1184]],

        [[-0.4376, -0.4372, -0.4368, -0.4363, -0.4356, -0.4349, -0.4341,
          -0.4332],
         [ 0.3223,  0.3214,  0.3204,  0.3193,  0.3182,  0.3170,  0.3157,
           0.3143],
         [-0.1223, -0.1218, -0.1213, -0.1207, -0.1202, -0.1196, -0.1190,
          -0.1184]]], device='cuda:0', grad_fn=<StackBackward0>)
```

**Comment by albertfgu** [comment]
Odd, I'm pretty sure it worked when I checked a few weeks ago. Regardless the chunking is a more advanced feature that doesn't affect the normal forward or step modes. If forward and step agree in that test then it should be correct. Did you look into the other suggestions in my last post? In particular the shape of the tensor in my test is different. Or pass in `S4Block(transposed=False)` for your test.

**Comment by xonobo** [comment]
`transposed=False` causes size mismatches at forward call (`y, final_state = s4(u, state=state)`). 
[Here is how I set the transposed option](https://github.com/xonobo/state-spaces/blob/399577ce66c33626010c18050227dbf39aee0296/verify.py#L84).

By the way, the y and ys differ as I mentioned above, but the state values of forward and step modes are exactly the same. 

```
final state:
 tensor([[[-0.0114-0.0544j,  0.0179+0.0196j],
         [-0.0338-0.1163j,  0.0396+0.0426j],
         [-0.0134-0.0615j,  0.0203+0.0222j]],

        [[-0.0114-0.0544j,  0.0179+0.0196j],
         [-0.0338-0.1163j,  0.0396+0.0426j],
         [-0.0134-0.0615j,  0.0203+0.0222j]]], device='cuda:0'


step final state:
 tensor([[[-0.0114-0.0544j,  0.0179+0.0196j],
         [-0.0338-0.1163j,  0.0396+0.0426j],
         [-0.0134-0.0615j,  0.0203+0.0222j]],

        [[-0.0114-0.0544j,  0.0179+0.0196j],
         [-0.0338-0.1163j,  0.0396+0.0426j],
         [-0.0134-0.0615j,  0.0203+0.0222j]]], device='cuda:0',
       grad_fn=<AddBackward0>)
```

By the way how convolution mode can ingest shorter sequences as input in chunking? I am a bit confused :(

**Comment by xonobo** [comment]
I followed the code and understood if I'm not wrong that the kernel is computed for the desired length of sequence in chunking. And even tried chunking of 1-length sequences with chunking and obtained exactly the same results for state and y outputs. 

I think whether step mode would be identical to chunking with 1-length sequences or not?

**Comment by albertfgu** [comment]
My test creates an input of shape `(B, H, L)` and requires the model to be constructed with `transposed=True`. Your original test created an input of shape `(B, L, H)` and requires the model to be constructed with `transposed=False`.

Step mode should be identical to chunking with chunk_length=1. If it's not matching for larger chunk sizes then there's probably a small error in the code. As I said this is not relevant to your original question. Chunking is independent of the forward and step modes.

**Comment by xonobo** [comment]
I just used the default S4 model given for BIDMC dataset. According to s4.yaml it is constructed with `transposed=false` as you said. 

I believe the step mode does not reproduce the y output for both of us. I can only verify the states of both modes. You can try it yourself with this [fork](https://github.com/xonobo/state-spaces) by just running the [verify.py](https://github.com/xonobo/state-spaces/blob/main/verify.py) script.

**Comment by albertfgu** [comment]
I thought your last post said the step was correct and only chunk is wrong.
Can you paste the full output of my test?
I’m unable to test at the moment, but I ran this very recently and stepping
(and full autoregressive generation) worked correctly.

**Comment by xonobo** [comment]
Here is the output of your script:
```
Adding path:  /home/bozkalay/workspace/state-spaces.xonobo
CUDA extension for structured kernels (Cauchy and Vandermonde multiplication) not found. Install by going to extensions/kernels/ and running `python setup.py install`, for improved speed and memory efficiency. Note that the kernel changed for state-spaces 4.0 and must be recompiled.
output:
 tensor([[[-0.2190, -0.2190, -0.2189, -0.2187, -0.2186, -0.2184, -0.2182,
          -0.2179],
         [ 0.2135,  0.2130,  0.2125,  0.2120,  0.2114,  0.2108,  0.2102,
           0.2096],
         [-0.2103, -0.2107, -0.2110, -0.2114, -0.2118, -0.2122, -0.2125,
          -0.2129]],

        [[-0.2190, -0.2190, -0.2189, -0.2187, -0.2186, -0.2184, -0.2182,
          -0.2179],
         [ 0.2135,  0.2130,  0.2125,  0.2120,  0.2114,  0.2108,  0.2102,
           0.2096],
         [-0.2103, -0.2107, -0.2110, -0.2114, -0.2118, -0.2122, -0.2125,
          -0.2129]]], device='cuda:0', grad_fn=<ReshapeAliasBackward0>) torch.Size([2, 3, 8])
final state:
 tensor([[[-0.0114-0.0544j,  0.0179+0.0196j],
         [-0.0338-0.1163j,  0.0396+0.0426j],
         [-0.0134-0.0615j,  0.0203+0.0222j]],

        [[-0.0114-0.0544j,  0.0179+0.0196j],
         [-0.0338-0.1163j,  0.0396+0.0426j],
         [-0.0134-0.0615j,  0.0203+0.0222j]]], device='cuda:0',
       grad_fn=<AddBackward0>) torch.Size([2, 3, 2])
step outputs:
 tensor([[[-0.4376, -0.4372, -0.4368, -0.4363, -0.4356, -0.4349, -0.4341,
          -0.4332],
         [ 0.3223,  0.3214,  0.3204,  0.3193,  0.3182,  0.3170,  0.3157,
           0.3143],
         [-0.1223, -0.1218, -0.1213, -0.1207, -0.1202, -0.1196, -0.1190,
          -0.1184]],

        [[-0.4376, -0.4372, -0.4368, -0.4363, -0.4356, -0.4349, -0.4341,
          -0.4332],
         [ 0.3223,  0.3214,  0.3204,  0.3193,  0.3182,  0.3170,  0.3157,
           0.3143],
         [-0.1223, -0.1218, -0.1213, -0.1207, -0.1202, -0.1196, -0.1190,
          -0.1184]]], device='cuda:0', grad_fn=<StackBackward0>)
step final state:
 tensor([[[-0.0114-0.0544j,  0.0179+0.0196j],
         [-0.0338-0.1163j,  0.0396+0.0426j],
         [-0.0134-0.0615j,  0.0203+0.0222j]],

        [[-0.0114-0.0544j,  0.0179+0.0196j],
         [-0.0338-0.1163j,  0.0396+0.0426j],
         [-0.0134-0.0615j,  0.0203+0.0222j]]], device='cuda:0',
       grad_fn=<AddBackward0>)
chunk outputs:
 tensor([[[-0.2190, -0.2190, -0.2189, -0.2187, -0.2186, -0.2184, -0.2182,
          -0.2179],
         [ 0.2135,  0.2130,  0.2125,  0.2120,  0.2114,  0.2108,  0.2102,
           0.2096],
         [-0.2103, -0.2107, -0.2110, -0.2114, -0.2118, -0.2122, -0.2125,
          -0.2129]],

        [[-0.2190, -0.2190, -0.2189, -0.2187, -0.2186, -0.2184, -0.2182,
          -0.2179],
         [ 0.2135,  0.2130,  0.2125,  0.2120,  0.2114,  0.2108,  0.2102,
           0.2096],
         [-0.2103, -0.2107, -0.2110, -0.2114, -0.2118, -0.2122, -0.2125,
          -0.2129]]], device='cuda:0', grad_fn=<CatBackward0>)
chunk final state:
 tensor([[[-0.0114-0.0544j,  0.0179+0.0196j],
         [-0.0338-0.1163j,  0.0396+0.0426j],
         [-0.0134-0.0615j,  0.0203+0.0222j]],

        [[-0.0114-0.0544j,  0.0179+0.0196j],
         [-0.0338-0.1163j,  0.0396+0.0426j],
         [-0.0134-0.0615j,  0.0203+0.0222j]]], device='cuda:0',
       grad_fn=<AddBackward0>)
```

**Comment by albertfgu** [comment]
Oh I do remember having to fix something in the step function. There’s a
missing activation after the S4 layer or something like that, you should be
able to figure it out by inspecting the forward vs step functions. If you
don’t find it I’ll look at it later when I get a chance.

**Comment by xonobo** [comment]
Hit the bull's eye. In the step function the activation after the s4 layer was missing. adding that activation resolved the issue.
