### ISSUE TITLE
Potential typo in standalone S4

### ISSUE THREAD

**Issue by alstonlo** [HazyResearch/state-spaces#118]
I just wanted to report what I think might be a typo in the standalone S4 code ([L1378-L1380](https://github.com/HazyResearch/state-spaces/blob/main/models/s4/s4.py#L1378-L1380)). I believe `self.kernel` should be `self.backend`, since the former attribute is not assigned.

**Comment by albertfgu** [comment]
Good catch, thanks, it has been fixed!

**Comment by alstonlo** [comment]
Thanks!
