### ISSUE TITLE
How to visualize the results of prediction?

### ISSUE THREAD

**Issue by lzmax888** [HazyResearch/state-spaces#12]
Hi,

Thank you for your sharing.

I am doing some experiments on Ett dataset using S4. 
I wonder how to load the best checkpoint, test it with new data, and then visualize the prediction and truth.

Is there any easy way by pytorch lighting?

Cheers,
Max

**Comment by krandiash** [comment]
Unfortunately, we don't have any visualization code available at the moment. For loading models back in and doing inference, I would recommend referring to our code for audio generation with SaShiMi (https://github.com/HazyResearch/state-spaces/blob/main/sashimi/generation.py) -- we load in a lightning checkpoint and then do inference there.

**Comment by lzmax888** [comment]
Cool. And where can I find the definitions of your config.yaml? 
Such as model.layer.hurwitz, model.layer.postact
Thank you

**Comment by albertfgu** [comment]
We recommend reading the basics of [Hydra](https://hydra.cc/docs/intro/) to understand the configuration system. The README also tells you where to look for these definitions.

For example, the `model.layer._name_` option can be looked up in the registry `src/utils/registry.py`, which tells you that the core model layer is `src.models.sequence.ss.s4.S4`. That points to a PyTorch nn.Module whose options include `hurwitz`, `postact`, etc.
