### ISSUE TITLE
Using Neumann series to compute the DFT of basis kernels directly

### ISSUE THREAD

**Issue by PeaBrane** [HazyResearch/state-spaces#125]
### Description
This is a semi question and a semi feature request (which I can try to work on potentially). Currently, it seems like the approach to compute the DFT of the basis kernels (at least for `S4D`) is to first explicitly materialize them, and then take the FFT of it. I think there is potentially a simpler and more efficient way to go about this in one-stage (without materializing the basis kernels in time-domain) using [Neumann series](https://en.wikipedia.org/wiki/Neumann_series).

### Context
Following the convention of [`s4d.py`](https://github.com/HazyResearch/state-spaces/blob/main/models/s4/s4d.py), and letting `tau = 2j * pi` for concision. If we take a single basis kernel to be `(dtA * arange(L)).exp()`, assuming `dtA` to be a scalar for sake of simplicitly. And we take some discrete Fourier basis to be `(tau * k * arange(L) / L).exp()`. The process of DFT is basically to take the dot product between the two and sum it up (repeat this for every Fourier basis `k`).

### Description
In other words, we are trying to evaluate `((dtA + tau * k / L) * arange(L)).exp().sum()`, which is simply a [Neumann series](https://en.wikipedia.org/wiki/Neumann_series), of which the sum can be analytically evaluate in O(1) time, something like this
```
exponent = dtA + tau * k / L
numerator = 1 - (exponent * (L + 1)).exp()
denominator = 1 - exponent.exp()
kernel_f = numerator / denominator
```

The following generalizations are straightforward:

- We need to do this for multiple modes `k`, but this is very easy to vectorize
- We need to do this for complex vector `dtA` (for S4D) or even matrix `dtA` (for S4), but Neumann series summation formula is still valid for these generalizations.

Something like this:
```
k = torch.arange(L)
exponent = dtA.unsqueeze(-1) + tau * k / L  # where dtA can be a vector or matrix
...  # the rest is the same
```

### Potential Benefits
I believe this can maybe get the complexity of compute the DFT of basis kernels down to O(L) from the O(L logL) of FFT, while increasing parallel efficiency and reducing memory transfers. At the scale of the whole network, I don't know how much we save by doing this, because I'm guessing the major bottleneck would still be other operations in the network (e.g. still needing to do FFT on the batched inputs).

**Comment by albertfgu** [comment]
You're right, it should be possible to speed up the calculation of `FFT(K)`. We didn't do this for the reasons you stated:
1. One still has to compute the FFT and iFFT of inputs, which also have an extra batch dimension so this would dominate the costs.
2. The entire fft-convolution can be fused into one kernel anyways (the FlashConv from the H3 paper, which should be available from their official repo). When this fusion happens the total memory transfers is the same and is the speed bottleneck, so doing this optimization even in the batch_size=1 case (which might save on 1 out of the 3 FFTs) wouldn't even impact the speed on GPUs.

**Comment by PeaBrane** [comment]
@albertfgu Thanks for the reply. Based on my understanding of the FlashConv method from the paper and this [test script](https://github.com/HazyResearch/H3/blob/main/csrc/fftconv/launch_fftconv.py), the fusion does not incorporate the generation of `K` nor their FFT transforms (though it probably can)
```
out = fftconv_fwd(u, k_f, D, dropout_mask, fft_size)
```
where `k_f` is already the FFT transformed full kernels.

If we generate basis kernels `K_f` via Neumann series, then the full kernels `k_f` can be obtained by just aggregating `K_f` channel-wise with the `C` matrix, which saves the O(H * L * log(L)) cost for doing the FFT from `k` to `k_f`. But you're probably right this saving would be pretty small for most tasks (even ignoring memory transfers). The saving would probably only be significant if the `batch_size` or `N` is exceedingly small compared to `H`. 

I can run some tests for going from the A and C matrix to `k_f` using the two methods, with different combinations of `(batch_size, N, H)`, to see whether the speed up is worth it.

**Comment by albertfgu** [comment]
Feel free to try it if you're interested!

**Comment by PeaBrane** [comment]
Hmm.. turns out the Neumann sum method did significantly worse than the current implementation (at least without any efforts for kernel fusion), for a typical setup where `H, N, L = 64, 64, 16384`. FFT did not appear to be a major bottleneck for `kernel_f` evaluation, and the Neumann sum method were significantly bottlenecked by elementwise operations like `sub`, `exp`, `div`, etc (memory bound?). I will verify everything is correct, and close this issue once verified. 

Here is the profiling code

```
import math

import torch
from torch.profiler import ProfilerActivity, profile

torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32 = True


def get_kernel_f_zoh(dtA, C, L, arange):
    K = (dtA.unsqueeze(-1) * arange).exp()
    kernel = torch.einsum('hnl,hn->hl', K, C)
    kernel_f = torch.fft.fft(kernel, n=2*L)
    return kernel_f


def get_kernel_f_neumann(dtA, C, L, krange):
    exponent = dtA.unsqueeze(-1) + krange
    numerator = 1 - (exponent * L).exp()
    denominator = 1 - exponent.exp()
    K_f = numerator / denominator
    kernel_f = torch.einsum('hnl,hn->hl', K_f, C)
    return kernel_f


H = 64
N = 64
L = 16384
dt = 0.0001

device = 'cuda:0'

j = torch.tensor(1j, dtype=torch.complex64, device=device)
arange = torch.arange(L, dtype=torch.float, device=device)
krange = -2 * math.pi * j * torch.arange(2 * L, dtype=torch.float, device=device) / L / 2

dtA = dt * torch.complex(-torch.rand(H, N, device=device), torch.rand(H, N, device=device))
C = dt * torch.complex(torch.rand(H, N, device=device), torch.rand(H, N, device=device))

with torch.inference_mode():
    with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA], 
                 schedule=torch.profiler.schedule(wait=5, warmup=0, active=100)) as prof:
        for i in range(105):
            get_kernel_f_zoh(dtA, C, L, arange)
            prof.step()
    print(prof.key_averages().table(sort_by="self_cuda_time_total", row_limit=7))
    
    with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA], 
                 schedule=torch.profiler.schedule(wait=5, warmup=0, active=100)) as prof:
        for i in range(105):
            get_kernel_f_neumann(dtA, C, L, krange)
            prof.step()
    print(prof.key_averages().table(sort_by="self_cuda_time_total", row_limit=7))
```

The current zoh method returned:
```
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg    # of Calls  
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                              aten::exp         0.20%     648.000us         0.29%     957.000us       9.570us     129.434ms        39.86%     137.623ms       1.376ms           100  
                          exp_kernel_vectorized4_kernel         0.00%       0.000us         0.00%       0.000us       0.000us     129.434ms        39.86%     129.434ms       1.294ms           100  
                                              aten::mul         0.73%       2.369ms         0.97%       3.152ms      31.520us     107.825ms        33.20%     111.462ms       1.115ms           100  
void at::native::elementwise_kernel<128, 4, at::nati...         0.00%       0.000us         0.00%       0.000us       0.000us     107.825ms        33.20%     107.825ms       1.078ms           100  
                                              aten::bmm         0.48%       1.572ms         0.69%       2.233ms      22.330us      67.712ms        20.85%      72.456ms     724.560us           100  
std::enable_if<true, void>::type internal::gemvx::ke...         0.00%       0.000us         0.00%       0.000us       0.000us      67.712ms        20.85%      67.712ms     677.120us           100  
                                         cuLaunchKernel         0.28%     918.000us         0.28%     918.000us       3.060us      21.078ms         6.49%      21.078ms      70.260us           300  
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
Self CPU time total: 325.797ms
Self CUDA time total: 324.751ms
```

And the Neumann sum method returned:
```
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg    # of Calls  
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                              aten::sub         0.06%       1.201ms         0.10%       2.026ms      10.130us     537.310ms        27.09%     575.198ms       2.876ms           200  
void at::native::vectorized_elementwise_kernel<4, at...         0.00%       0.000us         0.00%       0.000us       0.000us     537.310ms        27.09%     537.310ms       2.687ms           200  
                                              aten::exp         0.05%       1.101ms         0.08%       1.703ms       8.515us     525.076ms        26.47%     548.865ms       2.744ms           200  
                          exp_kernel_vectorized4_kernel         0.00%       0.000us         0.00%       0.000us       0.000us     525.076ms        26.47%     525.076ms       2.625ms           200  
                                              aten::div         0.03%     539.000us         0.05%     941.000us       9.410us     399.046ms        20.12%     422.104ms       4.221ms           100  
void at::native::vectorized_elementwise_kernel<4, at...         0.00%       0.000us         0.00%       0.000us       0.000us     399.046ms        20.12%     399.046ms       3.990ms           100  
                                              aten::mul         0.03%     691.000us         0.06%       1.184ms      11.840us     268.075ms        13.52%     288.077ms       2.881ms           100  
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
Self CPU time total: 2.077s
Self CUDA time total: 1.983s
```

**Comment by albertfgu** [comment]
Yeah, the exp and div operations probably slow it down a lot. It might be faster if you fuse the whole kernel, but then again the normal Vandermonde mult would also be the same speed if you fuse it. Thanks for investigating!
