### ISSUE TITLE
Error when running example.py

### ISSUE THREAD

**Issue by DorotheaKolossa** [HazyResearch/state-spaces#15]
Dear all, many thanks for this extremely interesting code (and maths)!

Running 
example.py --grayscale
with python 3.8 gives the following error on my system:
"RuntimeError: view_as_real doesn't work on unresolved conjugated tensors.  To resolve the conjugate tensor so you can view it as real, use self.resolve_conj(); however, be warned that the resulting tensor will NOT alias the original."

Maybe some requirements need specific versions for the example to run?

**Comment by albertfgu** [comment]
Are you using PyTorch 1.11? If so, this commit should have fixed the error:
https://github.com/HazyResearch/state-spaces/commit/83a9f136a6353648681cdd5dcc2a0eac48a69340
