### ISSUE TITLE
n_epoch_double

### ISSUE THREAD

**Issue by calderma** [HazyResearch/state-spaces#16]
Hello thank you for the great library. I was wondering about the n_epoch_double flag and the best way to use it. If you use that flag will it not just give you a cuda OOM error when it doubles? Or is the appropriate usage to begin with a very small batch size so that it has room to double without going OOM? When running the wt103 model if I went over L_max=4096 with a batch size of 1 on a 4xV100 32GB GPU machine I ran out of memory when it got to the eval stage of the first epoch. I have a language modeling use case that requires very long sequence lengths (8192+) and wanted to try the s4 model on it, because the results seem pretty good for lower sequence lengths. Any help would be appreciated. Thank you!

**Comment by albertfgu** [comment]
This flag was used in preliminary versions and hasn't been touched in awhile; I'm not even sure if it still works currently.
When this flag was used, the batch size was halved so the total number of tokens per batch was kept constant: https://github.com/HazyResearch/state-spaces/blob/83a9f136a6353648681cdd5dcc2a0eac48a69340/src/dataloaders/lm.py#L182

However, in my experiments, I found that just starting off with the long sequences worked perfectly fine. So I would recommend just starting off with the max sequence length you want.

**Comment by calderma** [comment]
Great thanks.
