### ISSUE TITLE
minGPT like training

### ISSUE THREAD

**Issue by Howuhh** [HazyResearch/state-spaces#2]
Hi! Very impressive results! 

I'd like to try applying the S4 model on some toy example from NLP, like text generation (replicate examples in minGPT from @karpathy).  I'm not very familiar with state-space models, so I don't understand a few things and have few questions:

1. As far as I understand, such model doesn't need positional encodings/embeddings? 
2. How to properly train such a model in causal mode, that is, so that the model doesn't look into the future? Is there some equivalent to masking in Transformers? Or it's default mode out of box (like in vanilla rnn)?

Thanks!

**Comment by albertfgu** [comment]
Thank you! Overall, one interpretation is that S4 can be viewed as a special RNN and so these properties are similar to RNNs

1. We don't use positional encodings for any experiments; the recurrence or dynamical system has a notion of "time" or "position"
2. The default model is causal out of the box

Hope this helps!
