### ISSUE TITLE
S4 Module Distribution

### ISSUE THREAD

**Issue by AmitMY** [HazyResearch/state-spaces#20]
I think it would be quite useful if one could install this repository, either directly from git or preferably using `pip`.

I invision a change to models where people only have to:
1. `pip install state-spaces`
2. `from state_spaces import S4`
3. replace use of `nn.LSTM` or `nn.Transformer` with `S4`

There is a package on pypi, not sure if it was pushed by you or not, but the latest version is older than the current code.
https://pypi.org/project/state-space/#history

**Comment by albertfgu** [comment]
This would definitely be very useful! That package is not ours, but we'll look into packaging the code up when possible. Some aspects of the model are still changing so I'm not exactly sure when, but it's definitely in our plans.

**Comment by AmitMY** [comment]
Hi @krandiash , this has been closed however I still can't find a distributed version.
