### ISSUE TITLE
Training on own data

### ISSUE THREAD

**Issue by davidmrau** [HazyResearch/state-spaces#23]
I'd like to train a sashimi model on my own data. Could you please let me know in what structure the data needs to be in order to be compatible with the dataloder?

**Comment by krandiash** [comment]
Closing this issue for now, feel free to reopen if you run into trouble.

**Comment by davidmrau** [comment]
@krandiash Thanks a lot. I got it to run. However, using a custom name threw an error so I just used the `youtubemix.yaml` and copied my files to `data/youtubemix`.
