### ISSUE TITLE
S4 for Seq2seq tasks?

### ISSUE THREAD

**Issue by Saltychtao** [HazyResearch/state-spaces#27]
Hello, 
 You have shown S4's great ability and efficiency on classification and unconditional generation (wikitext-103) tasks. I am wondering if S4 can be applied to conditional generation tasks such as summarization and machine translation?  A simple idea is to   re-organize these tasks to language modeling tasks, but I am not sure whether the generation quality would be affected.

**Comment by albertfgu** [comment]
This is a great idea! We haven't tried it yet, so we don't know how the generation quality will be - but we think there are many interesting conditional tasks where S4 might perform well, for example on the SCROLLS dataset for long range modeling. Feel free to follow up privately for more specific questions.
