### ISSUE TITLE
request to load logs for experiments

### ISSUE THREAD

**Issue by yuvalkirstain** [HazyResearch/state-spaces#3]
Hi, can you please upload the logs of the experiments that were reported in the paper?

I tried to reproduce the `wikitext-103` experiment but had to change some configurations due to hardware constraints. Even though the changes were minor, the results were not as I expected them to be. I think that the logs from the original experiments might help me to reproduce the results more easily.

Thank you so much!

**Comment by albertfgu** [comment]
Hi Yuval,

I've created a report with our original runs for this experiment:
https://wandb.ai/hazy-research/hippo/reports/S4-WikiText-103--VmlldzoxMzU0MjI1?accessToken=a3dkgaiu6i8omdkn0ul5eya8c2tftzxzf2bz3e1jgcfm1vv7tb1cxqy2ujdbzbxq

Hope this helps!
