### ISSUE TITLE
when running for language model exception happend 

### ISSUE THREAD

**Issue by mjtaheri11** [HazyResearch/state-spaces#31]
when I tried to run the code for the language model (wt103) with the command 
```bash
HYDRA_FULL_ERROR=1 python3 -m train wandb=null experiment=s4-wt103
``` 
the exception happened!

in `adaptive_softmax.py`  module, the left index is greater than r_idx so `nn.Parameter(torch.zeros(abs(r_idx - l_idx)))` can't pass (line 116)! so I did used `abs()` function to pass it.
then in `self.out_layers_weights` (line 182) again exception arises.  `list index out of range` so I did used `try-except` to pass the lines...

You can find the full error in the attached file: 
[error.txt](https://github.com/HazyResearch/state-spaces/files/8716007/error.txt)

**Comment by albertfgu** [comment]
I am not getting any errors with a fresh installation of the repo. It sounds like you have modified the code which makes it difficult to help. What happens with a clean installation when you don't modify the code?

Note that the config was slightly out of date with extra options that are now deprecated, so I just updated it to remove two lines. This shouldn't have caused your error though, so I don't know what's causing it.

**Comment by albertfgu** [comment]
All configs have been double checked, including the WikiText-103 config. This model has also been retrained and the weights released; see the READMEs.
