### ISSUE TITLE
how to save and load checkpoints

### ISSUE THREAD

**Issue by TsukimiRini** [HazyResearch/state-spaces#38]
Hi,
I'm running experiments with default settings using this command:
```shell
python -m train wandb=null experiment=sashimi-sc09
```
I'd like to get the checkpoint of the best model in the training process and then load it to generate `.wav` files. But i find the only checkpoint generated is a `last.ckpt` under  the directory `outputs/yyyy-mm-dd/xx-xx-xx/checkpoints`, and i have no idea how to load it (since the checkpoint loading in `sashimi/generation.py` loads a `.pt` file)

**Comment by krandiash** [comment]
Hi, thanks for bringing this issue to our attention. We will have an updated version of the generation script in the new `v3` release (coming soon) that allows you to load the `.ckpt` files directly and generate from them.

**Comment by albertfgu** [comment]
By the way, the [updated generation script](https://github.com/HazyResearch/state-spaces#generation) is available that allows generating from any new experiments run in this repository.
