### ISSUE TITLE
Time-series experiments

### ISSUE THREAD

**Issue by AndreRoehrig** [HazyResearch/state-spaces#4]
The experiments using datasets like etth, ettm, and ecl don't run (despite the definitions in /config). I think it's because the datasets cannot be downloaded automatically like the LRA experiments.

Would it be possible to add this, or explain how these experimets could be run?

**Comment by AndreRoehrig** [comment]
```
python -m train wandb=null experiment=s4-informer-etth
dataset appears more than once in the final defaults list

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by krandiash** [comment]
Hi, apologies about the delay, we've added the relevant code required to rerun these experiments. Please try the following e.g. to run ECL 168 length univariate:

```python -m train experiment=s4-informer-ecl decoder.mode=last dataset.size=[24,24,168] dataset.timeenc=1 dataset.variant=0 dataset.features=S model.n_layers=2 model.dropout=0.25 optimizer.lr=0.01 task.metrics=[mse,mae]```

Data for the experiments can be found [here](https://drive.google.com/file/d/1XqpxE6cthIxKYviSmR703yU45vdQ1oHT/view?usp=sharing). Make a `data` folder inside the state-spaces repo, and unzip the `informer.zip` file from the link inside that folder.
