### ISSUE TITLE
Replication of Diffusion Results

### ISSUE THREAD

**Issue by stefan-baumann** [HazyResearch/state-spaces#46]
Hi, I'm trying to replicate your results for applying SaShiMi in a diffusion context, and have run into some questions about implementation details along the way. It'd be awesome if you could help me out with them.

 1. I have found the diffusion version of the SaShiMi model at https://github.com/HazyResearch/state-spaces/blob/diffwave/sashimi/sashimi.py. I assume that one is the reference implementation. If yes, what parameters did you use? Just `bidirectional=True, unet=True, diffwave=True` and set the rest to the values specified in Appendix C.2.2 of the paper and their respective default values?
 2. In the original model, you use mu-law quantization for the model. Is this something you also use with the diffusion implementation? And are you using an embedding encoder & sequence decoder like for the AR model? If so, how are you implementing this setup, also in regards to e.g. the additive noise?

Best,
Stefan

**Comment by stefan-baumann** [comment]
Hi Albert,
Thank you very much for the incredibly quick help once again!
I already guessed that you were basing your implementation of that repo judging from the references in the reused code. It would be awesome if you could release a fork with your changes as you mention that can be used to replicate your results, especially as I have also been facing some issues stemming from the upsampling method in SaShiMi in my reproduction attempts.

**Comment by albertfgu** [comment]
My Diffwave implementation is released at https://github.com/albertfgu/diffwave-sashimi. It took longer than planned since I ended up improving the infra to make it easier to train new models, beyond just reproducing results.

**Comment by stefan-baumann** [comment]
Thank you very much! Doubly so for putting in all of the effort to improve it further to make working on it easier!
