### ISSUE TITLE
Difference between d_model and d_state?

### ISSUE THREAD

**Issue by andrewliu2001** [HazyResearch/state-spaces#47]

**Comment by albertfgu** [comment]
`d_model` is the dimension of the model backbone. It is the "hidden features" H in the papers. Think of it as the model dimension of a Transformer, or the number of channels in a CNN. It's the parameter to change to control model size.

`d_state` is the dimension of the SSM matrices, or "state size" N in the papers. You shouldn't need to adjust this (perhaps increasing it can help, but is usually pretty minor).
