### ISSUE TITLE
WikiText-103 model checkpoint

### ISSUE THREAD

**Issue by caesar-one** [HazyResearch/state-spaces#5]
Hi,

Are you planning to make the pretrained WikiText-103 model available? Thank you very much!

**Comment by krandiash** [comment]
Hi, we're looking into doing this -- we'll update the thread on this issue when we have more on that

**Comment by albertfgu** [comment]
Long time coming, but we now have a trained checkpoint that can generate text. It's referenced a few times in the READMEs, for example [here](https://github.com/HazyResearch/state-spaces#example-1-language).
