### ISSUE TITLE
Scaling Sashimi datasets

### ISSUE THREAD

**Issue by neale** [HazyResearch/state-spaces#61]
Hi! Thanks for open sourcing this collection of great work. 

I'm wondering about the scale of the datasets used to train sashimi -- and therefore S4. 
Taking YouTubeMix for example, at a 16K sample, chunked into 8s clips, it has about 1800 data points. 
This seems fairly small, and I'm wondering if there is a design choice here beyond ease of comparison with baselines. 
I suppose the paper was mostly concerned with better performance with long context lengths, rather than pushing fidelity specifically.
 
Is there some limitation that you foresee that precludes the use of a larger dataset (other than compute issues)?
I'm wondering how well sashimi would do with say, 100 YouTubeMix-length audio tracks.

**Comment by albertfgu** [comment]
I don't think there's any issues with larger datasets; we would be pretty interested in scaling properties. I think our datasets were chosen for standardization and compute considerations. I think we actually did start training something much larger like MAESTRO but the main problem was compute, but it was learning reasonably well.

**Comment by neale** [comment]
I see, MAESTRO looks reasonably sized. 
Thanks for the input.
