### ISSUE TITLE
Cannot reproduce the automatic evaluation metrics on sc09

### ISSUE THREAD

**Issue by gzhu06** [HazyResearch/state-spaces#64]
Hi, thanks for sharing this amazing work. 

I met some problems during reproducing the automatic evaluation metrics using wavenet, samplernn and sashimi on sc09 

For sashimi, I first followed the unconditional generation steps here: https://github.com/HazyResearch/state-spaces/tree/main/sashimi#unconditional-generation using the cmd:
```
python -m generate experiment=audio/sashimi-sc09 n_samples=10240 l_sample=16000 load_data=false checkpoint_path=./checkpoints/sashimi_sc09.pt
```

Then I followed the steps here: https://github.com/HazyResearch/state-spaces/tree/main/sashimi#automated-metrics and get:
```
------------------                                                                                              
Train Set Scores                                                                                                
------------------                                                                                              
        FID: -1.522326951997055e-10                                                                             
        Inception: 8.553013                                                                                     
        M Inception: 291.33218                                                                                  
        AM: 0.15689613                                                                                          
------------------                                                                                              
Test Set Scores                                                                                                 
------------------                                                                                              
        FID: 0.0220020280148132                                                                                 
        Inception: 8.329372                                                                                     
        M Inception: 253.32138                                                                                  
        AM: 0.18534964


Sample Scores (with Tuned Thresholds)       
        FID: 4.626722693291156
        Inception: 3.4318142
        M Inception: 14.08194
        AM: 1.1535671
```
The train/test scores are normal, but sample scores are way different from the paper. But when I used the sashimi-sc09 samples from huggingface, then it's the same as those values reported in the paper.

For samplernn, I got error:
```
"/state-spaces/src/models/baselines/samplernn.py", line 347, in step
    if self._step_idx > self.lookback:                                
  File "/.conda/envs/s4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__  
raise AttributeError("'{}' object has no attribute '{}'".format(AttributeError: 'SampleRNN' object has no attribute '_step_idx'

```

For wavent, I got error:

```
  File "/state-spaces/generate.py", line 157, in main                   
model.load_state_dict(state_dict)                                                   
  File "/state-spaces/train.py", line 215, in load_state_dict    
    return super().load_state_dict(state_dict, strict=strict)                  
  File "/.conda/envs/s4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict                                                     
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(  
RuntimeError: Error(s) in loading state_dict for SequenceLightningModule:   
        Missing key(s) in state_dict: "encoder.0.weight", "decoder.0.output_transform.weight", "decoder.0.output_transform.bias".                                                               
        Unexpected key(s) in state_dict: "encoder.weight", "decoder.output_transform.weight", "decoder.output_transform.bias".
```

Any ideas on what cause these problems? Thanks in advance!

By the way, my torch version is:
pytorch                   1.10.1          py3.8_cuda10.2_cudnn7.6.5_0    pytorch

**Comment by albertfgu** [comment]
Thanks for the report! The results from in the paper are for an earlier version of the model; the checkpoint should still be available on the HF hub and generation should work with the v2 tag of this codebase. The current checkpoint is for a reproduction run with the current version of S4 (v3) that was slightly worse on NLL (1.903 vs 1.891 in the paper), and I didn't check the generation results. I listened to the samples and they sounded reasonable, but it's possible they're actually worse than the original model.

I actually have an even better model with the current code (v3) that gets 1.873 NLL but I haven't released it. When I have time, I'll check the samples for these models and look into the other errors as well.

**Comment by gzhu06** [comment]
Thank you for your quick reply! I'll try sashimi under v2 tag tomorrow and will report the results then.

**Comment by gzhu06** [comment]
Okay, I followed v2 and get the following results:

Sashimi:
------------------                                                                                              
Sample Scores (with Tuned Thresholds)                                                                           
------------------                                                                                              
        FID: 2.029431239451447                                                                                  
        Inception: 4.31139                                                                                      
        M Inception: 25.875378                                                                                 
        AM: 0.8816196

The rest models also work. Looking forward to a future fix for v3. Thanks!

**Comment by albertfgu** [comment]
I've pushed some changes that should make all the generation work with the latest version of code. There is also a new Sashimi config and model checkpoint that has significantly better results on SC09.
