### ISSUE TITLE
Resuming suspended training

### ISSUE THREAD

**Issue by ag1988** [HazyResearch/state-spaces#7]
Hey folks,

Congrats on the amazing and inspiring work!! 

I have a quick question - how do I resume training + wandb logging if the training got terminated before completion. E.g. say the original command was `CUDA_VISIBLE_DEVICES=0 python -m train experiment=s4-lra-pathx loader.batch_size=16 trainer.accumulate_grad_batches=2` and the training got suspended halfway through the full training. What command should I run to resume the training and the wandb logging?

Thanks in advance,
Ankit

**Comment by krandiash** [comment]
Hi thanks for the question!

You can resume training by passing in a path to the checkpoint using the `trainer.resume_from_checkpoint` flag. So for example,

```bash
CUDA_VISIBLE_DEVICES=0 python -m train experiment=s4-lra-pathx loader.batch_size=16 trainer.accumulate_grad_batches=2 trainer.resume_from_checkpoint=/path/to/checkpoint
```

This will start another wandb run that picks up where the last one left off. You'll want to point to the `last.ckpt` file that gets saved to the logging folder (your training logs should point you to where that is).

**Comment by ag1988** [comment]
Thank you so much for the prompt response Karan! I'll follow your
instructions and let you know if I have any further questions!

Regards,
Ankit

**Comment by ag1988** [comment]
Btw just so that I get it right, you mentioned that wandb will pick up from where the last run left off. That means that it wont copy the logs of the previous run and will appear as a partial run on the dashboard, right?

**Comment by krandiash** [comment]
That's right: you should see a new (partial) run on the dashboard.
