### ISSUE TITLE
Multi-layer S4 code release

### ISSUE THREAD

**Issue by mrsamsami** [HazyResearch/state-spaces#71]
I want to use deep S4, but the only multi-layer S4 that has been released is the [simpler version](https://github.com/HazyResearch/state-spaces/blob/main/src/models/s4/s4d.py), which lacks the recurrent mode. Can you share the S4 code with multiple layers?

**Comment by albertfgu** [comment]
That file is a minimal implementation intended to help with understanding the model. The real implementation is in the same folder, see the README there https://github.com/HazyResearch/state-spaces/tree/main/src/models/s4

**Comment by mrsamsami** [comment]
As far as I understand the code, there is only a single layer in the full implementation, right?

**Comment by albertfgu** [comment]
Yes, just as in all deep learning models, you have to construct a backbone that uses layers of your choice such as convolutions, attention, or S4. You can look at any CNN or Transformer architecture to learn how to do this.

In this codebase, you can find examples of how to construct such a deep model [here](https://github.com/HazyResearch/state-spaces/blob/292984cbda8df6644eba41102feab552c77ca3bc/example.py#L153) or [here](https://github.com/HazyResearch/state-spaces/blob/main/src/models/sequence/model.py).
