### ISSUE TITLE
Getting example.py up and running

### ISSUE THREAD

**Issue by symlons** [HazyResearch/state-spaces#73]
Hi, I am trying to get the example.py script running. I am getting the folliwing errors:

<img width="1157" alt="Screenshot 2022-11-05 at 5 22 51 PM" src="https://user-images.githubusercontent.com/63979635/200130288-c7acfb16-48b6-4847-ae4f-9baf58670a69.png">
<img width="1057" alt="Screenshot 2022-11-05 at 5 23 08 PM" src="https://user-images.githubusercontent.com/63979635/200130291-ce3e6663-f371-46d3-b6c7-9d1df584aca6.png">

What might I have to change to get the script running?
Thanks in advance.

**Comment by albertfgu** [comment]
I haven't seen this issue before. Are you on Pytorch 1.10, 1.11, or 1.12? Can you paste the command you used and the full error message?

**Comment by symlons** [comment]
I am using Pytorch 1.10. And I am running the example.py script with: `python3 example.py`
<img width="1157" alt="Screenshot 2022-11-05 at 6 36 55 PM" src="https://user-images.githubusercontent.com/63979635/200134580-ad888e11-f133-421f-b5c6-a76e63ef9836.png">

**Comment by albertfgu** [comment]
I have an environment in Pytorch 1.10.1 that is working fine. My Python version is 3.8.12 (which really shouldn't make a difference) and this script has been tested on CUDA 10.2, 11.1, and 11.3.

It's weird that the error happens in the torch dataloader. Is it possible that other parts of the environment are not installed correctly? For example, your torchvision version should be 0.11. Are you able to run any other Pytorch example scripts on this environment? Also, perhaps you can delete the cached dataset `data/cifar`.

**Comment by symlons** [comment]
Yes, the issue was with torchvision.
I solved it by upgrading torchvision: `pip install torchvision==0.13.1+cu113`
Seems like torchvision was still defaulting to an older version of cuda.
