### ISSUE TITLE
Inaccuracies in documentation and open questions

### ISSUE THREAD

**Issue by RoiEXLab** [HazyResearch/state-spaces#74]
So I'm trying to build a model using sashimi that generates sound using a custom dataset. In order to achieve this I tried to replicate the `generate.py` script, but using the standalone variant of sashimi.

During this process I ran into some issues that were in my opinion results of inaccurate (or more likely outdated) documentation.

The `sashimi/README.md` file states this:
https://github.com/HazyResearch/state-spaces/blob/292984cbda8df6644eba41102feab552c77ca3bc/sashimi/README.md?plain=1#L113-L127

However this command out of the box fails for a couple of reasons. First of all `wandb=false` is not passed. Not a major problem because this is stated multiple times throughout the documentation, so I added it but it still didn't succeed because `sashimi-youtubemix` is not a valid experiment name. Instead you have to prepend `audio/` so the script picks it up correctly. But even then it still does not work because the generation script tries to look for a non-existent checkpoint file. I did download it and put it in the right folder (according to the README), but it did not pick it up. Instead I had to pass an additional `checkpoint_path=checkpoints/sashimi_youtubemix.pt` to get it finally working.

I believe subtleties like those happen a lot in command examples stated in your README files.

So I ran the generation in a debugger to find out what is going on and found some discrepancies between the standalone sashimi model and the built-in version that the documentation can't seem to explain.

Here is how I believe the built-in generation works (autoregressive, sashimi, unconditional):
1. Initialize the "seed" tensor to silence (or whatever 128 is in mu law encoding) and pass that to the encoder for a single step
2. use the encoded values to feed the sashimi model
3. use the sashimi output to get a unnormalized probability distribution where pytorch's `Categorical` picks a sample from using weighted probabilities. This is where the "noise" is introduced to not all samples result in the same audio.
4. Feed this sample back into the encoder and repeat for the next sample

This seems pretty reasonable, but there are some things about this I don't quite understand:

1. How does the standalone `sashimi.setup_rnn()` play any role here? I thought the RNN config was to speed up generation? Is it setup by some other mechanism or is it dropped in order to generalize the generate script for all different kinds of models?
2. How does the RNN config handle noise? According to the example (see below) a random tensor with noise is initialized and directly fed into the model without any encoding or decoding mechanism. It is also never fed back to the input. Is this intended because the `state` does store the intermediate data, or does resubmitting the initial noise kill any reasonable time dependencies that are desirable?

https://github.com/HazyResearch/state-spaces/blob/292984cbda8df6644eba41102feab552c77ca3bc/sashimi/README.md?plain=1#L41-L63

Thanks in advance for your time.

**Comment by albertfgu** [comment]
Thanks for the report and sorry for any inconveniences.

> First of all wandb=false is not passed.

I took this out to err on the side of having logs for new users, but it's documented in so many places that it should be fine

> still didn't succeed because sashimi-youtubemix is not a valid experiment name. Instead you have to prepend audio/ so the script picks it up correctly

This is a mistake, thanks for catching it! The correct experiment names could be found a few lines above in the README

> Instead I had to pass an additional checkpoint_path=checkpoints/sashimi_youtubemix.pt to get it finally working.

Yep, this is all documented in the documentation for the main generation script. It looked like this part of the sashimi config wasn't updated correctly.


> So I ran the generation in a debugger to find out what is going on and found some discrepancies between the standalone sashimi model and the built-in version that the documentation can't seem to explain.

I'm not quite sure what you mean by this, but I think the confusion is that the code snippet in `sashimi/README.md` is *not* for autoregressive generation. It's just a simple demo of how to use Sashimi in RNN mode; this snippet simply produces a tensor `ys` from RNN mode that should be equal to the output of normal CNN mode, i.e. `ys == sashimi(x)` (up to numerical accuracy). The main `generate.py` script is the only one that should be used for AR generation.

> How does the standalone sashimi.setup_rnn() play any role here? I thought the RNN config was to speed up generation? Is it setup by some other mechanism or is it dropped in order to generalize the generate script for all different kinds of models?

The `sashimi.setup_rnn` function is just a convenience to convert its internals S4 modules from CNN to RNN mode. If you look at the [definition](https://github.com/HazyResearch/state-spaces/blob/292984cbda8df6644eba41102feab552c77ca3bc/sashimi/sashimi.py#L418), it's just 2 lines that calls a setup function for each S4 layer. The main generation script has the [same logic](https://github.com/HazyResearch/state-spaces/blob/292984cbda8df6644eba41102feab552c77ca3bc/generate.py#L190) but more explicitly.

> How does the RNN config handle noise? According to the example (see below) a random tensor with noise is initialized and directly fed into the model without any encoding or decoding mechanism. It is also never fed back to the input. Is this intended because the state does store the intermediate data, or does resubmitting the initial noise kill any reasonable time dependencies that are desirable?

The linked snippet is just an example of RNN mode. It's been updated to state this more clearly.

**Comment by RoiEXLab** [comment]
@albertfgu Ah, thanks a lot for clarifying. I think I got it now. Thank you for updating the documentation. I just have a final remaining question left in this case, which I believe is an intentional design choice on your end.

You initialize the "seed tensor" with silence. Wouldn't it be better to initialize it with random noise to get more potential variance in results? Or is there different reason for it?

**Comment by albertfgu** [comment]
Variance will come with the model's generated outputs (the sampling at every timestep as you noted above). Conditioning on noise doesn't make sense because the model has never seen noise during training. Conditioning means you're asking the model "what comes next after this sequence of samples?" which doesn't make sense if the sample is synthetic and not part of the data distribution. Consider the two cases:

* Unconditional generation: Since nothing is being conditioned on, there is no difference between noise or silence
* Conditional generation: the conditioning prompt should be part of the data distribution. Best is to take a prefix of an example from the dataset, which is usually what you want to do https://github.com/HazyResearch/state-spaces/blob/06e0f62eae1a6ba0288c516da3739ad6c13a37a6/generate.py#L220

**Comment by RoiEXLab** [comment]
Thank you very much
