### ISSUE TITLE
Unable to reproduce the results of S4 on pathx

### ISSUE THREAD

**Issue by sheryc** [HazyResearch/state-spaces#82]
Hi,

I recently tried to reproduce the results reported in the HTTYP paper. By using the default configs provided in `experiment/lra/` folder, I was able to reproduce all but pathx's results. The training and validation accuracy remains 0.5 during training.

To reproduce the problem: I was using the current head commit (https://github.com/HazyResearch/state-spaces/commit/06dbbdfd0876501a7f12bf3262121badbc7658af). The command: `python3 train.py experiment=lra/s4-lra-pathx wandb=null train.seed=2222`.

My conda environment:
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
_sysroot_linux-64_curr_repodata_hack 3                   haa98f57_10
absl-py                   1.2.0                    pypi_0    pypi
aim                       3.15.2                   pypi_0    pypi
aim-ui                    3.15.2                   pypi_0    pypi
aimrecords                0.0.7                    pypi_0    pypi
aimrocks                  0.2.1                    pypi_0    pypi
aiofiles                  0.8.0                    pypi_0    pypi
aiohttp                   3.8.1                    pypi_0    pypi
aiohttp-cors              0.7.0                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
alembic                   1.8.1                    pypi_0    pypi
allennlp-models           2.9.3                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     3.6.1                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
asttokens                 2.0.8                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
autopage                  0.5.1                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
background                0.2.1                    pypi_0    pypi
base58                    2.0.1                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
binutils_impl_linux-64    2.35.1               h27ae35d_9
binutils_linux-64         2.35.1              h454624a_30
blas                      1.0                         mkl
bleach                    5.0.1                    pypi_0    pypi
blessed                   1.19.1                   pypi_0    pypi
blis                      0.7.8                    pypi_0    pypi
boto3                     1.22.6                   pypi_0    pypi
botocore                  1.25.13                  pypi_0    pypi
brotlipy                  0.7.0           py39h27cfd23_1003
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2022.9.24            ha878542_0    conda-forge
cached-path               1.1.2                    pypi_0    pypi
cachetools                5.2.0                    pypi_0    pypi
catalogue                 2.0.8                    pypi_0    pypi
cauchy-mult               0.0.0                    pypi_0    pypi
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.0           py39hd667e15_1
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.0.4                    pypi_0    pypi
cliff                     4.0.0                    pypi_0    pypi
cloudpickle               2.0.0                    pypi_0    pypi
cmaes                     0.8.2                    pypi_0    pypi
cmd2                      2.4.2                    pypi_0    pypi
colorful                  0.5.4                    pypi_0    pypi
colorlog                  6.6.0                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
conllu                    4.4.1                    pypi_0    pypi
contourpy                 1.0.5                    pypi_0    pypi
cryptography              37.0.1           py39h9ce1e76_0
cudatoolkit               11.3.1               h2bc3f7f_2
cycler                    0.11.0                   pypi_0    pypi
cymem                     2.0.6                    pypi_0    pypi
datasets                  2.4.0                    pypi_0    pypi
debugpy                   1.6.3                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
dill                      0.3.5.1                  pypi_0    pypi
distlib                   0.3.6                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
einops                    0.4.1                    pypi_0    pypi
einsum                    0.3.0                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 1.1.1                    pypi_0    pypi
fairscale                 0.4.6                    pypi_0    pypi
fastapi                   0.67.0                   pypi_0    pypi
fastjsonschema            2.16.2                   pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.6.0                    pypi_0    pypi
fonttools                 4.37.3                   pypi_0    pypi
freetype                  2.11.0               h70c0345_0
frozenlist                1.3.1                    pypi_0    pypi
fsspec                    2022.7.1                 pypi_0    pypi
ftfy                      6.1.1                    pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gcc_impl_linux-64         9.3.0               h6df7d76_17
gcc_linux-64              9.3.0               h1ee779e_30
giflib                    5.2.1                h7b6447c_0
gitdb                     4.0.9                    pypi_0    pypi
gitpython                 3.1.27                   pypi_0    pypi
gmp                       6.2.1                h295c915_3
gnutls                    3.6.15               he1e5248_0
google-api-core           2.8.2                    pypi_0    pypi
google-auth               2.9.1                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-cloud-core         2.3.2                    pypi_0    pypi
google-cloud-storage      2.5.0                    pypi_0    pypi
google-crc32c             1.3.0                    pypi_0    pypi
google-resumable-media    2.3.3                    pypi_0    pypi
googleapis-common-protos  1.56.4                   pypi_0    pypi
gpustat                   1.0.0                    pypi_0    pypi
greenlet                  1.1.2                    pypi_0    pypi
grpcio                    1.43.0                   pypi_0    pypi
gxx_impl_linux-64         9.3.0               hbdd7822_17
gxx_linux-64              9.3.0               h7e70986_30
h11                       0.13.0                   pypi_0    pypi
h5py                      3.7.0                    pypi_0    pypi
huggingface-hub           0.5.1                    pypi_0    pypi
hydra-colorlog            1.2.0                    pypi_0    pypi
hydra-core                1.2.0                    pypi_0    pypi
hydra-optuna-sweeper      1.2.0                    pypi_0    pypi
hydra-ray-launcher        1.2.0                    pypi_0    pypi
idna                      3.3                pyhd3eb1b0_0
importlib-metadata        4.12.0                   pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
intel-openmp              2020.2                      254
ipdb                      0.13.9                   pypi_0    pypi
ipykernel                 6.16.0                   pypi_0    pypi
ipython                   8.5.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.2                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h7f8727e_0
jsonnet                   0.18.0                   pypi_0    pypi
jsonschema                4.16.0                   pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            7.4.2                    pypi_0    pypi
jupyter-console           6.4.4                    pypi_0    pypi
jupyter-core              4.11.1                   pypi_0    pypi
jupyter-server            1.21.0                   pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        3.0.3                    pypi_0    pypi
keopscore                 2.1                      pypi_0    pypi
kernel-headers_linux-64   3.10.0              h57e8cba_10
kiwisolver                1.4.4                    pypi_0    pypi
lame                      3.100                h7b6447c_0
langcodes                 3.3.0                    pypi_0    pypi
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.35.1               h7274673_9
libffi                    3.3                  he6710b0_2
libgcc-devel_linux-64     9.3.0               hb95220a_17
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libiconv                  1.16                 h7f8727e_2
libidn2                   2.3.2                h7f8727e_0
libpng                    1.6.37               hbc83047_0
libstdcxx-devel_linux-64  9.3.0               hf0c5c8d_17
libstdcxx-ng              11.2.0               h1234567_1
libtasn1                  4.16.0               h27cfd23_0
libtiff                   4.2.0                h2818925_1
libunistring              0.9.10               h27cfd23_0
libuv                     1.40.0               h7b6447c_0
libwebp                   1.2.2                h55f646e_0
libwebp-base              1.2.2                h7f8727e_0
lmdb                      1.3.0                    pypi_0    pypi
lz4-c                     1.9.3                h295c915_1
mako                      1.2.1                    pypi_0    pypi
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.6.0                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mistune                   2.0.4                    pypi_0    pypi
mkl                       2020.2                      256
mkl-service               2.3.0            py39he8ac12f_0
mkl_fft                   1.3.0            py39h54f3939_0
mkl_random                1.0.2            py39h63df603_0
more-itertools            8.13.0                   pypi_0    pypi
msgpack                   1.0.4                    pypi_0    pypi
multidict                 6.0.2                    pypi_0    pypi
multiprocess              0.70.13                  pypi_0    pypi
murmurhash                1.0.7                    pypi_0    pypi
mysqlclient               2.1.1                    pypi_0    pypi
nbclassic                 0.4.5                    pypi_0    pypi
nbclient                  0.7.0                    pypi_0    pypi
nbconvert                 7.2.1                    pypi_0    pypi
nbformat                  5.7.0                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3
nest-asyncio              1.5.6                    pypi_0    pypi
nettle                    3.7.3                hbbd107a_1
networkx                  2.8.5                    pypi_0    pypi
nltk                      3.7                      pypi_0    pypi
notebook                  6.5.1                    pypi_0    pypi
notebook-shim             0.2.0                    pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
numpy-base                1.19.2           py39h2ae0177_0
nvidia-ml-py              11.495.46                pypi_0    pypi
oauthlib                  3.2.0                    pypi_0    pypi
omegaconf                 2.2.2                    pypi_0    pypi
opencensus                0.11.0                   pypi_0    pypi
opencensus-context        0.1.3                    pypi_0    pypi
openh264                  2.1.1                h4ff587b_0
openssl                   1.1.1o               h166bdaf_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
optuna                    2.10.1                   pypi_0    pypi
overrides                 6.1.0                    pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.4.3                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pathy                     0.6.2                    pypi_0    pypi
pbr                       5.10.0                   pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickle5                   0.0.11                   pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.0.1            py39h22f2fdc_0
pip                       21.2.4           py39h06a4308_0
platformdirs              2.5.3                    pypi_0    pypi
plotly                    5.10.0                   pypi_0    pypi
pluggy                    1.0.0                    pypi_0    pypi
pot                       0.8.2                    pypi_0    pypi
preshed                   3.0.6                    pypi_0    pypi
prettytable               3.4.0                    pypi_0    pypi
prometheus-client         0.13.1                   pypi_0    pypi
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.31                   pypi_0    pypi
protobuf                  3.19.4                   pypi_0    pypi
psutil                    5.9.1                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
py-rouge                  1.1                      pypi_0    pypi
py-spy                    0.3.14                   pypi_0    pypi
py3nvml                   0.2.7                    pypi_0    pypi
pyarrow                   9.0.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pybind11                  2.10.0                   pypi_0    pypi
pybind11-global           2.6.1                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pydantic                  1.8.2                    pypi_0    pypi
pydeprecate               0.3.1                    pypi_0    pypi
pygments                  2.12.0                   pypi_0    pypi
pykeops                   2.1                      pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.9                    pypi_0    pypi
pyperclip                 1.8.2                    pypi_0    pypi
pyrootutils               1.0.4                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0
pytest                    7.1.2                    pypi_0    pypi
python                    3.9.12               h12debd9_1
python-dateutil           2.8.2                    pypi_0    pypi
python-dotenv             0.20.0                   pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.11.0          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-lightning         1.5.10                   pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2022.1                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     24.0.1                   pypi_0    pypi
qtconsole                 5.4.0                    pypi_0    pypi
qtpy                      2.3.0                    pypi_0    pypi
ray                       1.12.0                   pypi_0    pypi
readline                  8.1.2                h7f8727e_1
regex                     2022.7.25                pypi_0    pypi
requests                  2.28.0           py39h06a4308_0
requests-oauthlib         1.3.1                    pypi_0    pypi
responses                 0.18.0                   pypi_0    pypi
restrictedpython          5.2                      pypi_0    pypi
rich                      12.5.1                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
s3transfer                0.5.2                    pypi_0    pypi
sacremoses                0.0.53                   pypi_0    pypi
scikit-learn              1.1.2                    pypi_0    pypi
scipy                     1.8.1                    pypi_0    pypi
seaborn                   0.12.0                   pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
sentencepiece             0.1.96                   pypi_0    pypi
sentry-sdk                1.9.2                    pypi_0    pypi
setproctitle              1.3.1                    pypi_0    pypi
setuptools                59.5.0                   pypi_0    pypi
shortuuid                 1.0.9                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1
sklearn                   0.0                      pypi_0    pypi
smart-open                5.2.1                    pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
spacy                     3.2.4                    pypi_0    pypi
spacy-legacy              3.0.9                    pypi_0    pypi
spacy-loggers             1.0.3                    pypi_0    pypi
sqlalchemy                1.4.39                   pypi_0    pypi
sqlite                    3.38.5               hc218d9a_0
srsly                     2.4.4                    pypi_0    pypi
stack-data                0.5.1                    pypi_0    pypi
starlette                 0.14.2                   pypi_0    pypi
stevedore                 4.0.0                    pypi_0    pypi
sysroot_linux-64          2.17                h57e8cba_10
tenacity                  8.1.0                    pypi_0    pypi
tensorboard               2.10.0                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorboardx              2.5.1                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.16.0                   pypi_0    pypi
textblob                  0.17.1                   pypi_0    pypi
thinc                     8.0.17                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
tokenizers                0.12.1                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
torchaudio                0.11.0               py39_cu113    pytorch
torchmetrics              0.9.3                    pypi_0    pypi
torchtext                 0.12.0                   pypi_0    pypi
torchvision               0.12.0               py39_cu113    pytorch
tornado                   6.2                      pypi_0    pypi
tqdm                      4.64.0                   pypi_0    pypi
traitlets                 5.4.0                    pypi_0    pypi
transformers              4.18.0                   pypi_0    pypi
typer                     0.4.2                    pypi_0    pypi
typing-utils              0.1.0                    pypi_0    pypi
typing_extensions         4.1.1              pyh06a4308_0
tzdata                    2022a                hda174b7_0
urllib3                   1.26.13                  pypi_0    pypi
uvicorn                   0.18.2                   pypi_0    pypi
virtualenv                20.16.6                  pypi_0    pypi
wandb                     0.13.7                   pypi_0    pypi
wasabi                    0.10.1                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.4.1                    pypi_0    pypi
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
widgetsnbextension        4.0.3                    pypi_0    pypi
word2number               1.1                      pypi_0    pypi
xmltodict                 0.13.0                   pypi_0    pypi
xxhash                    3.0.0                    pypi_0    pypi
xz                        5.2.5                h7f8727e_1
yarl                      1.8.1                    pypi_0    pypi
zipp                      3.8.1                    pypi_0    pypi
zlib                      1.2.12               h7f8727e_2
zstd                      1.5.2                ha4553b6_0

Thank you for your time,
Suyuchen

**Comment by albertfgu** [comment]
Thanks for the report! I'll try to reproduce the experiments again, but last I checked they worked. Here are a couple things that might help:
1. Can you try going back to an earlier commit? I don't think any commits in the last two months should have changed anything, but I also didn't reproduce LRA experiments since then so it might be safer to go back to October or so (say, commit `292984c`)
2. Can you uninstall and reinstall the Cauchy CUDA extension after checking out the commit? Also, have you tried any other models (e.g. any of the S4D variants) or only the main S4 model?
3. What GPU type are you using? I've only run these experiments on A100s; it's possible that other GPUs can have small discrepancies in numerics. (Although this particular experiment also won't fit on anything smaller than an A100 and would be too slow to be worth running anyways).

Note that the S4 experiment should start learning within 1-2 epochs, so you don't have to run the experiment to the end to debug this.

**Comment by albertfgu** [comment]
I ran the experiment at the tip commit (same as yours) and reproduced the results (at least, it started learning by 1-2 epochs). I am on PyTorch 1.13.0 and recompiled the CUDA kernel.

**Comment by sheryc** [comment]
Thank you for your reply! I still cannot train the model, but the problem might be from the data. I'll re-download the dataset and rerun.

**Comment by albertfgu** [comment]
Have you made in progress in figuring out the issue here?

**Comment by MahmudulAlam** [comment]
@sheryc Have you made any progress? I am facing a similar issue. Perhaps the data is corrupted which is the only thing I added to the repo.

@albertfgu Can you please upload your data to the cloud and share the link?

**Comment by albertfgu** [comment]
Instructions for downloading the data are in the README.

https://github.com/HazyResearch/state-spaces/tree/main/src/dataloaders#long-range-arena-lra

**Comment by MahmudulAlam** [comment]
I downloaded data again from here: https://storage.googleapis.com/long-range-arena/lra_release.gz and used the lra_release/lra_release/pathfinder128 directory for the pathx task. still no sign of convergence.

**Comment by albertfgu** [comment]
What is your PyTorch version, GPU, and are you using the CUDA extension?

**Comment by MahmudulAlam** [comment]
PyTorch: 1.13.1+cu116
Running on a single NVIDIA TESLA PH402 32GB GPU 
Yes, I have installed the CUDA extension.

**Comment by albertfgu** [comment]
I have never tested it with that GPU. I don't know if it's possible that small numerical issues could make a difference. Do the other datasets produce the right results?

If it's a matter of small differences in the computation, perhaps using hyperparameters that make it easier to learn might help. You can try lowering the learning rate and increasing the number of warmup steps. For example add on `optimizer.lr=0.0002 model.layer.lr=0.0001 scheduler.num_warmup_steps=50000` (you may need to double check the flag names). If that doesn't work then I'm not sure what is happening.

**Comment by MahmudulAlam** [comment]
I tested the cifar10 in example.py that worked and the accuracy was exactly reproduced. I will try tuning the hyperparameters.

**Comment by yhl48** [comment]
Has anyone made any progress on this? I am training it with V100 and run into the same issue as well

**Comment by MahmudulAlam** [comment]
@yhl48 we faced this issue and it was resolved after training it with A100. You could try the same.

**Comment by yhl48** [comment]
@MahmudulAlam thanks! I can now replicate the results using V100, it just takes longer
