### ISSUE TITLE
MACs

### ISSUE THREAD

**Issue by lucadellalib** [HazyResearch/state-spaces#89]
Hi,
I'm trying to measure the MACs of S4D using [ptflops](https://github.com/sovrasov/flops-counter.pytorch), but I get the following result:
```
(kernel): SSKernel(
            0, 0.000% Params, 0.0 Mac, 0.000% MACs, 
            (kernel): SSKernelDiag(0, 0.000% Params, 0.0 Mac, 0.000% MACs, )
          )
```
It looks like the tool cannot compute the MACs for `SSKernelDiag`, do you maybe know a way to compute it both in theory and in practice?

**Comment by albertfgu** [comment]
I'm not sure what the convention is for how to count MACs. I can give you the asymptotic flops of the main operations but I don't know how they map to MACs
1. Try commenting out the kernel construction and convolution and run it through the counter to get the MACs for the rest of the network
2. The kernel construction has $O(HNL)$ flops (where H is model dimension, N is state size, L is sequence length), probably with low constant factor
3. The convolution has three FFTs which are each $O(B H L \log L)$ flops (where B is batch size), probably with high constant factor

**Comment by mannykao** [comment]
You can use Albert's formulae and add an entry to 'flops_counter.py' for SSKernelDiag.
