### ISSUE TITLE
'legsd' got deleted from transition() in model/s4/s4.py

### ISSUE THREAD

**Issue by jchia** [HazyResearch/state-spaces#97]
In commit 57f3a8e1, the case for 'legsd' got deleted from `transition()`. However, `dplr()` still uses 'legsd' in calling `nplr()`, which in turn calls `transition()` with 'legsd'.  The result:
```
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import s4.s4
CUDA extension for structured kernels (Cauchy and Vandermonde multiplication) not found. Install by going to extensions/kernels/ and running `python setup.py install`, for improved speed and memory efficiency. Note that the kernel changed for state-spaces 4.0 and must be recompiled.
Falling back on slow Cauchy and Vandermonde kernel. Install at least one of pykeops or the CUDA extension for better speed and memory efficiency.
>>> s4.s4.dplr()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jchia/gh/state-spaces/models/s4/s4.py", line 519, in dplr
    A, _, _, _ = nplr('legsd', N)
  File "/home/jchia/gh/state-spaces/models/s4/s4.py", line 391, in nplr
    A, B = transition(measure, N)
  File "/home/jchia/gh/state-spaces/models/s4/s4.py", line 343, in transition
    raise NotImplementedError
NotImplementedError
```

Is this intended or a bug? Is dplr(init='hippo') now an obsolete use case so the 'hippo' case should also be removed from dplr()? But init='hippo' is the current default.

Consequently, `s4.SSMKernelDiag(init='diag-legs', d_model=8)` also does not work (crashes for the same reason in `transition()`), i.e. 'diag-legs' is no longer supported. Is this intended?

**Comment by albertfgu** [comment]
Thanks for the catch! The latest commit (https://github.com/HazyResearch/state-spaces/commit/593dbe4b9cc862d2b4cdfe5ff7b523c67937928d) should have fixed it.

The reason this happened is because you actually no longer need to pass in `init=diag-legs` to use S4D; the default init argument (`init=legs`) is equivalent. So I was testing with the latter and didn't catch this error. Passing in `init=diag-hippo` is just an alias for `init=diag-legs` and is also equivalent.

**Comment by jchia** [comment]
I didn't realize src/models/sequence/kernels/dplr.py also had this problem, but I was referring to models/s4/s4.py. Does models/s4/s4.py:519 need a similar fix?

**Comment by albertfgu** [comment]
The standalone files are copy/pasted from the normal model path which are factored in a more modular way and might have more options. Sometimes I forget to update/maintain both. Thanks for the PR!

**Comment by jchia** [comment]
Is it the case that the purpose of the standalone models/s4/s4.py is mainly ease-of-integration by people who want to use S4 in their own programs, and it's downstream of src/models/sequence/kernels/ssm.py in terms of code changes? Which one was used for the experiments in the papers?
